### PR TITLE
Remove legacy checks for read/write permissions.

### PR DESCRIPTION
**Pull request by djanowski**
Tested with latest version of the plugin, everything works smoothly.

### CODE REVIEW

**Comment by noahcooper** [comment]
Thanks for this PR! Do you happen to have some reference to a page on the Facebook Developer site, perhaps an entry in the changelog, that indicates that apps can now request both read and publish permissions at the same time? https://developers.facebook.com/docs/facebook-login/ios/permissions/ seems to suggest that this is still the case.

**Comment by djanowski** [comment]
@noahcooper Thanks for looking at this so quickly and for your pointer! You're right, it seems this is still the case (however the link to learn more on that section is broken.) It's not clear to me whether this is a policy by Apple or Facebook, or whether Facebook would error out if requesting read and publish permissions together. If this is a policy by Facebook, and Facebook errors out if requesting both read and publish permissions, then I don't think the plugin needs to duplicate this logic? The developer would see the error presented by Facebook immediately. It's late over here but I can do some tests tomorrow.

In any case, after I upgraded to this version of the plugin, Facebook started to complain about me requesting `manage_pages`. This is correct -- I also upgraded to the new, granular permissions, and everything works.

The new permissions I need are all prefixed with `pages_`. The plugin isn't catching those as "publish permissions", and everything works correctly, no complaint from Facebook.

**Comment by noahcooper** [comment]
@djanowski you make a valid point -- I'll test further just to confirm that no uncaught exception is thrown by the Facebook SDK if both read and publish permissions are requested at once, if not, I don't see any reason to duplicate this logic in the plugin. (To your point, the check to determine if a given permission is a publish permission is not even up-to-date because the syntax of Facebook permission names has long since changed, and in fact, some of the permissions referenced as publish permissions were deprecated years ago.

Would you mind updating your PR to make the same change on Android?

**Comment by noahcooper** [comment]
The more I look at this, I don't think it's a good idea to remove the current error handling from the plugin. Reason being that on Android, we actually need to keep this as-is, because the Android SDK has two completely different methods for logging in depending on the type of permission (`logInWithPublishPermissions` vs. `logInWithReadPermissions`). Removing the error handling on iOS would make the plugin's login method inconsistent on iOS and Android.

Instead, I think the best path forward is to try to update the plugin's private methods that check for publish permissions so that they are up-to-date with permission naming conventions in 2021.

**Comment by noahcooper** [comment]
@djanowski I've merged your changes for iOS and updated Android as well. In my testing, everything works as expected.

**Comment by djanowski** [comment]
Thank you @noahcooper! 🙏 ✨

**Pull request merged**
