### PR TITLE
(feat): Support GDPR Compliance

### LINKED ISSUE #7: FR: Support GDPR Compliance
**Bug or feature request**

[ ] I'm reporting a reproducible issue with the code
[X] I'm reporting a feature request

**Describe the Bug of feature request**

As of the EU data protection law, we are not allowed to send FB Events before the user accepts this. As the Facebook SDK automatically sends Install and Open Events that is a Problem. I found this: https://developers.facebook.com/docs/app-events/gdpr-compliance/

Is it possible for you to implement this *Delaying Automatic Event Collection* Feature?

**Expected Behavior**

As far as i understand it works like this: By setting the Variable to delay the events these events are queued and only fired to facebook after **Settings.isAutoLogAppEventsEnabled** is set back to `true` via Code?

### PR DESCRIPTION
**Pull request by EinfachHans**
fixes #7

- Add `FACEBOOK_AUTO_LOG_EVENTS` Variable
- Add `setAutoLogAppEventsEnabled` Method
- Add explanation in **readme**

### CODE REVIEW

**Comment by noahcooper** [comment]
Thanks for the PR @EinfachHans! Is there a reason to require the developer to update `Info.plist` themselves, rather than doing this in the plugin?

**Comment by EinfachHans** [comment]
I was unsure about how to do that based on the variable as we have to set it as an boolean? 🤔

**Comment by EinfachHans** [comment]
@noahcooper other Plugins mostly have scripts for that i think, as `<bool>$SOME_VARIABLE</bool>` doesn't work? 🤔 It's `<false />` or `<true />` directly...

**Comment by noahcooper** [comment]
Yeah, I think the simplest solution will be to use a hook to do this, since I don't think there's any way to use a variable as a Boolean in plugin.xml in this way. I need to think about that a little more.

In the meantime, would you mind rebasing with the develop branch to address the merge conflict? And could I bother you to clean up the unnecessary whitespace changes?

**Comment by EinfachHans** [comment]
@noahcooper yes hook should work here - For the moment i think the user set this by his own is acceptable. 🤔Merge conflict should be resolved, but i have no idea what is causing these white spaces changes... i rebased and explicit checked in my idea that they are not there and now they are here again? Is that a huge problem?

**Comment by EinfachHans** [comment]
@noahcooper okay finally managed my idea to remove the whitespaces

**Comment by noahcooper** [comment]
This looks good. I'll go ahead and merge this as-is, and if I can't get a hook working to update the plist before cutting the next release, that's OK.

Thanks for the PR!

**Comment by noahcooper** [comment]
@EinfachHans I've updated the iOS `after_prepare` hook to handle this automatically. (If a developer does happen to update `Info.plist` in their app's config file, that will take precedence over the plugin.)

Thanks again for the contribution!

**Comment by EinfachHans** [comment]
awesome!! 😊

**Pull request merged**
